version: "3.9"

services:
  api_products:
    container_name: api_products
    build:
      context: ./
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - product_backend-network
    command: ["sh", "-c", "until nc -z postgres 5432; do sleep 1; done; java -jar app.jar"]

  postgres:
    image: postgres:14.3-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - 5432:5432
    networks:
      - product_backend-network
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  product_backend-network:
    driver: bridge
