name: CI

on:
  push:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: Build and push GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: target/*.jar

      - name: Run tests
        run: mvn test
